from __future__ import annotations

ORDER_STATUS_CREATED = "created"
ORDER_STATUS_SEARCHING = "searching_driver"
ORDER_STATUS_ACCEPTED = "accepted"
ORDER_STATUS_ON_THE_WAY = "driver_on_the_way"
ORDER_STATUS_NEARBY = "driver_nearby_leave_now"
ORDER_STATUS_ARRIVED = "arrived"
ORDER_STATUS_IN_PROGRESS = "ride_in_progress"
ORDER_STATUS_COMPLETED = "completed"
ORDER_STATUS_CANCELLED = "cancelled"

ORDER_STATUS_FLOW = (
    ORDER_STATUS_SEARCHING,
    ORDER_STATUS_ACCEPTED,
    ORDER_STATUS_ON_THE_WAY,
    ORDER_STATUS_NEARBY,
    ORDER_STATUS_ARRIVED,
    ORDER_STATUS_IN_PROGRESS,
    ORDER_STATUS_COMPLETED,
)

DRIVER_ALLOWED_TRANSITIONS: dict[str, tuple[str, ...]] = {
    ORDER_STATUS_SEARCHING: (ORDER_STATUS_ACCEPTED,),
    ORDER_STATUS_ACCEPTED: (ORDER_STATUS_ON_THE_WAY, ORDER_STATUS_CANCELLED),
    ORDER_STATUS_ON_THE_WAY: (ORDER_STATUS_NEARBY, ORDER_STATUS_CANCELLED),
    ORDER_STATUS_NEARBY: (ORDER_STATUS_ARRIVED, ORDER_STATUS_CANCELLED),
    ORDER_STATUS_ARRIVED: (ORDER_STATUS_IN_PROGRESS, ORDER_STATUS_CANCELLED),
    ORDER_STATUS_IN_PROGRESS: (ORDER_STATUS_COMPLETED,),
    ORDER_STATUS_COMPLETED: (),
    ORDER_STATUS_CANCELLED: (),
}

ACTIVE_ORDER_STATUSES = (
    ORDER_STATUS_SEARCHING,
    ORDER_STATUS_ACCEPTED,
    ORDER_STATUS_ON_THE_WAY,
    ORDER_STATUS_NEARBY,
    ORDER_STATUS_ARRIVED,
    ORDER_STATUS_IN_PROGRESS,
)

CHAT_KIND_OPERATOR = "operator"
CHAT_KIND_RIDE = "ride"

SENDER_PASSENGER = "passenger"
SENDER_DRIVER = "driver"
SENDER_OPERATOR = "operator"

CAR_CLASS_ECONOM = "econom"
CAR_CLASS_COMFORT = "comfort"
CAR_CLASS_BUSINESS = "business"
CAR_CLASSES = (CAR_CLASS_ECONOM, CAR_CLASS_COMFORT, CAR_CLASS_BUSINESS)

PAYMENT_CASH = "cash"
PAYMENT_CARD = "card"
PAYMENT_SBP = "sbp"
PAYMENT_METHODS = (PAYMENT_CASH, PAYMENT_CARD, PAYMENT_SBP)

PASSENGER_STATUS_ACTIVE = "active"
PASSENGER_STATUS_BANNED = "banned"

DEFAULT_SMS_CODE = "1111"
SESSION_TTL_HOURS = 24 * 30
